### ISSUE TITLE
versionDescriptor missing

### ISSUE THREAD

**Issue by christophano** [auth0-extensions/auth0-deploy-extensions#32]
I have setup the deployment extension to automatically deploy from our source control on Azure Dev Ops.
Initially it worked but, when we migrated to a branch per tenant pattern, it stopped working.
The web hook fires and deployment starts, but it fails with the error:
```
Value cannot be null.

Parameter name: versionDescriptor
```
It's also worth noting that, on the table showing deployment history, the branch field is empty. I have tried removing and reinstalling the extension, but the result is the same.

**Comment by zxan1285** [comment]
Hi @christophano 
I wasn't able to reproduce this error. Could you please provide more details?
Which version control system do you use - git or azure devops?
Could you share screenshot of the extension settings, without sensitive information?

**Comment by christophano** [comment]
Hi @zxan1285, sure.
We use git repositories, hosted on Azure Dev Ops.
I have the following settings configured:
```yaml
TYPE: Git
REPOSITORY: Auth0
BRANCH: tenants/{tenantName}
INSTANCE: {dev ops organisation name}
COLLECTION: DefaultCollection
USERNAME: {my Dev Ops username}
AUTH_METHOD: Personal Access Token
TOKEN: {my personal access token}
BASE_DIR:
ENABLE_CIPHER: Yes
CIPHER_PASSWORD: {my password}
AUTH0_ALLOW_DELETE: No
SLACK_INCOMING_WEBHOOK:
```
Re: username - as I understand it, this part isn't actually used when using a personal access token, but it is a required field. It is the same username that generated the token though.
Re: slack webhook - this is currently blank, but worked fine previously.
One thing to note is, if I hit "deploy" from the deployments page on the extension, it works perfectly. If it triggers from the Dev Ops service hook then it fails.

The settings on my service hook in Dev Ops are:
```yaml
Trigger:
  Event: Code Pushed
  Filters:
    Repository: Auth0
    Branch: tenants/{tenantName}
Action:
  Type: Post via HTTP
  Settings:
    URL: {the Payload URL from the extension}
    HTTP Headers: {the HTTP Headers from the extension}
```
All other settings are the defaults.
